### ISSUE TITLE
Meaningless functions

### ISSUE THREAD

**Issue by breeswish** [pingcap/ng-monitoring#31]
https://github.com/pingcap/ng-monitoring/blob/f78b41562b9677caef38c7067000d378050ef216/component/conprof/util/misc.go#L7

**Comment by crazycs520** [comment]
em... It is a common function to generate profile timestamp.

**Comment by breeswish** [comment]
time.Unix() already generates a timestamp. Why do we need it?

**Comment by crazycs520** [comment]
`GetTimeStamp` will be used in many places, it was used to disambiguation.

Both `Unix()` and `UnixNano()` can generate a timestamp, but when I write code, I should choose which one? So I think add  a global function to use everywhere is better.

**Comment by breeswish** [comment]
I don't get your idea. As you said there can be disambiguation. So it is more clear when calling `Unix()` and `UnixNano()` directly, that you will know what it is generating (second precision timestamp, or nano second precision timestamp) just from reading the code. Calling `Timestamp()` just creates ambiguation: what timestamp is it generating? A second precision timestamp? A nanosecond precision timestamp?

**Comment by breeswish** [comment]
The quality (readibility and maintainibility) of your code depends on how easy it is to read your code, not how easy it is to write your code. There is never any code quality related with how easy you can write something.

If you judge your code quality by how easy you can write the code, then you are wrong. The easiest way to write a code is hacking, no commenting, copying. And they are all the **oppositie direction** of good engineering.

**Comment by crazycs520** [comment]
How about renaming to `GetUnixTsByTime`?

**Comment by breeswish** [comment]
No. `time.Unix()` is standard, well documented, plenty of materials and everyone know how to use. How do you think `GetUnixTsByTime()` is better than `time.Unix()`?

**Comment by crazycs520** [comment]
I will show you an example. Suppose `data` struct has a field which name is `ts`. When I write or query data, I need to set the field `ts` value, so every time I set the `ts` value, I need to decide which function should I use: `Unix()` or `UnixNano()`. even I add a comment about `ts`, I still need to jump to the `ts` comment and then know I should use `Unix()` instead `UnixNano()`.  But if I define a `GetUnixTsByTime ` global function, I can always just use it without thinking or decition.

**Comment by breeswish** [comment]
No. Here are the reaons:

1. Only you know that the `ts` field should use `GetUnixTsByTime` or `GetTimeStamp` and no other people can know this convention. How do you ensure that other people will corectly use your `GetUnixTsByTime` when reading or writing values into `ts`?

2. To resolve 1, the correct way is to make it clear that `ts` is a second precision timestamp. You can reveal this fact via either its name or its type. For example, by naming the field `unix_ts`, it is very clear that what it is stored, and what kind of things we should write to it.

3. By default when referring to `(Unix) Timestamp`, it is in second precision, in all programming languages, in all places. The value produced by `UnixNano()` should be never called "unix timestamp". It is only a unix-timestamp like things that has nanosecond precision. So, when you use `ts` in the code, and see `ts` in the code, you should better ensure that it is the unix timestamp, to reduce the ambiguation. So, if you ever write any field like `update_ts` without any comments, you should make it a unix timestamp (in second precision).

4. What if you want a higher precision timestamp? Then, still, name it in the field name. For example, `update_ts_nanos`. This makes it very clear for every people to know what it contains, and how people should use it, without the necessarily of reading the rest of the code.
